import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-soft": "var(--bg-soft)",
        ink: "var(--ink)",
        "ink-muted": "var(--ink-muted)",
        "ink-faint": "var(--ink-faint)",
        rule: "var(--rule)",
        "rule-strong": "var(--rule-strong)",
        accent: {
          DEFAULT: "var(--accent)",
          ink: "var(--accent-ink)",
        },
        indigo: {
          signal: "var(--indigo)",
        },
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        display: ["var(--font-fraunces)", "ui-serif", "Georgia", "serif"],
      },
      letterSpacing: {
        mono: "0.14em",
        tight2: "-0.025em",
        tight3: "-0.045em",
      },
      maxWidth: {
        editorial: "84rem",
      },
      typography: () => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": "var(--ink)",
            "--tw-prose-headings": "var(--ink)",
            "--tw-prose-lead": "var(--ink)",
            "--tw-prose-links": "var(--accent)",
            "--tw-prose-bold": "var(--ink)",
            "--tw-prose-counters": "var(--ink-muted)",
            "--tw-prose-bullets": "var(--ink-muted)",
            "--tw-prose-hr": "var(--rule)",
            "--tw-prose-quotes": "var(--ink)",
            "--tw-prose-quote-borders": "var(--accent)",
            "--tw-prose-captions": "var(--ink-muted)",
            "--tw-prose-code": "var(--ink)",
            "--tw-prose-pre-code": "var(--ink)",
            "--tw-prose-pre-bg": "var(--bg-soft)",
            "--tw-prose-th-borders": "var(--rule-strong)",
            "--tw-prose-td-borders": "var(--rule)",
            color: "var(--ink)",
            fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
            maxWidth: "none",
            h1: {
              fontFamily: "var(--font-fraunces), ui-serif, Georgia, serif",
              fontWeight: "600",
              fontVariationSettings: '"opsz" 96',
              letterSpacing: "-0.025em",
              lineHeight: "1.05",
            },
            h2: {
              fontFamily: "var(--font-fraunces), ui-serif, Georgia, serif",
              fontWeight: "600",
              fontVariationSettings: '"opsz" 48',
              letterSpacing: "-0.02em",
              lineHeight: "1.1",
            },
            h3: {
              fontFamily: "var(--font-fraunces), ui-serif, Georgia, serif",
              fontWeight: "600",
              fontVariationSettings: '"opsz" 32',
              letterSpacing: "-0.015em",
            },
            h4: {
              fontFamily: "var(--font-fraunces), ui-serif, Georgia, serif",
              fontWeight: "600",
              fontVariationSettings: '"opsz" 24',
            },
            a: {
              textDecoration: "none",
              borderBottom: "1px solid var(--accent)",
              fontWeight: "500",
              transition: "color 200ms ease, background 200ms ease",
              "&:hover": {
                backgroundColor: "var(--accent)",
                color: "var(--accent-ink)",
              },
            },
            blockquote: {
              fontFamily: "var(--font-fraunces), ui-serif, Georgia, serif",
              fontStyle: "italic",
              fontWeight: "400",
              fontVariationSettings: '"opsz" 32',
              borderLeftWidth: "2px",
              paddingLeft: "1.5em",
            },
            "blockquote p:first-of-type::before": { content: '""' },
            "blockquote p:last-of-type::after": { content: '""' },
            code: {
              fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
              fontWeight: "500",
              padding: "0.125em 0.375em",
              borderRadius: "2px",
              backgroundColor: "var(--bg-soft)",
              border: "1px solid var(--rule)",
              fontSize: "0.875em",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: {
              fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
              borderRadius: "2px",
              border: "1px solid var(--rule)",
              padding: "1.25rem 1.5rem",
              fontSize: "0.875rem",
              lineHeight: "1.6",
            },
            "pre code": {
              backgroundColor: "transparent",
              border: "0",
              padding: "0",
              fontWeight: "400",
            },
            hr: {
              borderColor: "var(--rule)",
              marginTop: "3em",
              marginBottom: "3em",
            },
            img: {
              borderRadius: "2px",
              border: "1px solid var(--rule)",
            },
            "ul > li::marker": { color: "var(--accent)" },
            "ol > li::marker": { color: "var(--accent)" },
          },
        },
        invert: {
          css: {
            "--tw-prose-body": "var(--ink)",
            "--tw-prose-headings": "var(--ink)",
            "--tw-prose-lead": "var(--ink)",
            "--tw-prose-links": "var(--accent)",
            "--tw-prose-bold": "var(--ink)",
            "--tw-prose-counters": "var(--ink-muted)",
            "--tw-prose-bullets": "var(--ink-muted)",
            "--tw-prose-hr": "var(--rule)",
            "--tw-prose-quotes": "var(--ink)",
            "--tw-prose-quote-borders": "var(--accent)",
            "--tw-prose-captions": "var(--ink-muted)",
            "--tw-prose-code": "var(--ink)",
            "--tw-prose-pre-code": "var(--ink)",
            "--tw-prose-pre-bg": "var(--bg-soft)",
            "--tw-prose-th-borders": "var(--rule-strong)",
            "--tw-prose-td-borders": "var(--rule)",
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
