import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-soft": "var(--bg-soft)",
        surface: "var(--surface)",
        ink: "var(--ink)",
        "ink-muted": "var(--ink-muted)",
        "ink-faint": "var(--ink-faint)",
        rule: "var(--rule)",
        "rule-strong": "var(--rule-strong)",
        accent: {
          DEFAULT: "var(--accent)",
          soft: "var(--accent-soft)",
          ink: "var(--accent-ink)",
        },
        indigo: {
          signal: "var(--accent)",
        },
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "monospace"],
        display: ["var(--font-space)", "var(--font-geist-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      letterSpacing: {
        mono: "0.16em",
        tight2: "-0.022em",
        tight3: "-0.035em",
      },
      borderRadius: {
        card: "14px",
        btn: "10px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(16,17,21,0.04), 0 8px 24px -12px rgba(16,17,21,0.10)",
        "card-hover": "0 2px 4px rgba(16,17,21,0.05), 0 16px 40px -16px rgba(16,17,21,0.16)",
      },
      maxWidth: {
        editorial: "80rem",
      },
      typography: () => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": "var(--ink)",
            "--tw-prose-headings": "var(--ink)",
            "--tw-prose-lead": "var(--ink)",
            "--tw-prose-links": "var(--accent)",
            "--tw-prose-bold": "var(--ink)",
            "--tw-prose-counters": "var(--ink-muted)",
            "--tw-prose-bullets": "var(--ink-muted)",
            "--tw-prose-hr": "var(--rule)",
            "--tw-prose-quotes": "var(--ink)",
            "--tw-prose-quote-borders": "var(--accent)",
            "--tw-prose-captions": "var(--ink-muted)",
            "--tw-prose-code": "var(--ink)",
            "--tw-prose-pre-code": "var(--ink)",
            "--tw-prose-pre-bg": "var(--bg-soft)",
            "--tw-prose-th-borders": "var(--rule-strong)",
            "--tw-prose-td-borders": "var(--rule)",
            color: "var(--ink)",
            fontFamily: "var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif",
            maxWidth: "none",
            h1: {
              fontFamily: "var(--font-space), var(--font-geist-sans), sans-serif",
              fontWeight: "600",
              letterSpacing: "-0.03em",
              lineHeight: "1.05",
            },
            h2: {
              fontFamily: "var(--font-space), var(--font-geist-sans), sans-serif",
              fontWeight: "600",
              letterSpacing: "-0.022em",
              lineHeight: "1.15",
            },
            h3: {
              fontFamily: "var(--font-space), var(--font-geist-sans), sans-serif",
              fontWeight: "600",
              letterSpacing: "-0.018em",
            },
            h4: {
              fontFamily: "var(--font-space), var(--font-geist-sans), sans-serif",
              fontWeight: "600",
            },
            a: {
              textDecoration: "none",
              color: "var(--accent)",
              borderBottom: "1px solid var(--accent-soft)",
              fontWeight: "500",
              transition: "border-color 200ms ease",
              "&:hover": {
                borderBottomColor: "var(--accent)",
              },
            },
            blockquote: {
              fontFamily: "var(--font-space), var(--font-geist-sans), sans-serif",
              fontStyle: "normal",
              fontWeight: "500",
              letterSpacing: "-0.01em",
              borderLeftWidth: "2px",
              paddingLeft: "1.5em",
            },
            "blockquote p:first-of-type::before": { content: '""' },
            "blockquote p:last-of-type::after": { content: '""' },
            code: {
              fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
              fontWeight: "500",
              padding: "0.125em 0.375em",
              borderRadius: "6px",
              backgroundColor: "var(--bg-soft)",
              border: "1px solid var(--rule)",
              fontSize: "0.875em",
            },
            "code::before": { content: '""' },
            "code::after": { content: '""' },
            pre: {
              fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
              borderRadius: "6px",
              border: "1px solid var(--rule)",
              padding: "1.25rem 1.5rem",
              fontSize: "0.875rem",
              lineHeight: "1.6",
            },
            "pre code": {
              backgroundColor: "transparent",
              border: "0",
              padding: "0",
              fontWeight: "400",
            },
            hr: {
              borderColor: "var(--rule)",
              marginTop: "3em",
              marginBottom: "3em",
            },
            img: {
              borderRadius: "6px",
              border: "1px solid var(--rule)",
            },
            "ul > li::marker": { color: "var(--accent)" },
            "ol > li::marker": { color: "var(--accent)" },
          },
        },
        invert: {
          css: {
            "--tw-prose-body": "var(--ink)",
            "--tw-prose-headings": "var(--ink)",
            "--tw-prose-lead": "var(--ink)",
            "--tw-prose-links": "var(--accent)",
            "--tw-prose-bold": "var(--ink)",
            "--tw-prose-counters": "var(--ink-muted)",
            "--tw-prose-bullets": "var(--ink-muted)",
            "--tw-prose-hr": "var(--rule)",
            "--tw-prose-quotes": "var(--ink)",
            "--tw-prose-quote-borders": "var(--accent)",
            "--tw-prose-captions": "var(--ink-muted)",
            "--tw-prose-code": "var(--ink)",
            "--tw-prose-pre-code": "var(--ink)",
            "--tw-prose-pre-bg": "var(--bg-soft)",
            "--tw-prose-th-borders": "var(--rule-strong)",
            "--tw-prose-td-borders": "var(--rule)",
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};

export default config;
